// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VinotecaRecu.Data;

#nullable disable

namespace VinotecaRecu.Migrations
{
    [DbContext(typeof(VinotecaRecuContext))]
    partial class VinotecaRecuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("VinotecaRecu.Data.Entities.Cata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Invitados")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("WineIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catas");
                });

            modelBuilder.Entity("VinotecaRecu.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Pa$$w0rd",
                            Rol = 0,
                            Username = "mgs@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Cl4ve!",
                            Rol = 0,
                            Username = "jhonwick@gmail.com"
                        });
                });

            modelBuilder.Entity("VinotecaRecu.Data.Entities.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variety")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Wines");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 21, 17, 56, 7, 649, DateTimeKind.Utc).AddTicks(5114),
                            Name = "Malbec",
                            Region = "Mendoza",
                            Stock = 30,
                            Variety = "Malbec",
                            Year = 2020
                        },
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 21, 17, 56, 7, 649, DateTimeKind.Utc).AddTicks(4479),
                            Name = "Cabernet Sauvignon",
                            Region = "Mendoza",
                            Stock = 50,
                            Variety = "Cabernet Sauvignon",
                            Year = 2018
                        });
                });

            modelBuilder.Entity("WineCata", b =>
                {
                    b.Property<int>("CataId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CataId", "WineId");

                    b.HasIndex("WineId");

                    b.ToTable("WineCata");
                });

            modelBuilder.Entity("WineCata", b =>
                {
                    b.HasOne("VinotecaRecu.Data.Entities.Cata", null)
                        .WithMany()
                        .HasForeignKey("CataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VinotecaRecu.Data.Entities.Wine", null)
                        .WithMany()
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
